#include "lighting.h"

#include "../graphics/graphics.h"

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>         // value_ptr (hand a matrix to OpenGL)
#include <xatlas/xatlas.h>

#include <vector>
#include <iostream>
#include <map>


std::vector<Light*> lights;
float ambient = 0.4f;
std::vector<Tri> occluders;
std::vector<std::pair<glm::vec3, glm::vec3>> lightGrid;

// for finding the bounds box of the scene for light grid
float minX = INFINITY;
float maxX = -INFINITY;
float minY = INFINITY;
float maxY = -INFINITY;
float minZ = INFINITY;
float maxZ = -INFINITY;


// Möller-Trumbore algorithm to check if a ray hits any occluders.
// FUNCTION GENERATED BY CLAUDE *** AI ALERT!!! ***
static bool rayOccluded(const glm::vec3& origin, const glm::vec3& dir,
                        float maxDist, const std::vector<Tri>& tris)
{
    const float EPS = 1e-6f;

    for (const Tri& t : tris)
    {
        glm::vec3 e1 = t.b - t.a;
        glm::vec3 e2 = t.c - t.a;
        glm::vec3 p  = glm::cross(dir, e2);
        float det = glm::dot(e1, p);
        if (glm::abs(det) < EPS) continue;   // ray runs parallel to the triangle

        float invDet = 1.0f / det;
        glm::vec3 tv = origin - t.a;

        float u = glm::dot(tv, p) * invDet;
        if (u < 0.0f || u > 1.0f) continue;

        glm::vec3 q = glm::cross(tv, e1);
        float v = glm::dot(dir, q) * invDet;
        if (v < 0.0f || u + v > 1.0f) continue;

        float hit = glm::dot(e2, q) * invDet;
        if (hit > EPS && hit < maxDist) return true;   // blocked before the light
    }
    return false;
}
// FUNCTION GENERATED BY CLAUDE *** AI ALERT!!! ***

glm::vec3 sampleLightAt(const glm::vec3& p)
{
    glm::vec3 lit(ambient);

    for (Light*& light : lights)
    {
        glm::vec3 toLight = light->pos - p;
        float dist = glm::length(toLight);
        if (dist > light->radius) continue;
        glm::vec3 dir = glm::normalize(toLight);

        if (rayOccluded(p, dir, dist, occluders)) continue;
        
        float a = 1/(1+(dist/light->falloff)*(dist/light->falloff));
        float b = 1/(1+(light->radius/light->falloff)*(light->radius/light->falloff));
        float denom = 1 - b;

        float atten = light->intensity * (a - b) / denom;
        atten = std::max(atten, 0.0f); // this line kinda useless but better safe than sorry
        lit += light->color * atten;
    }
    // if r, g, or b is over 1.0f then divide them all by the largest one. this
    // will force the values between 0 and 1 while still preserving the hue
    float peak = glm::max(lit.r, glm::max(lit.g, lit.b));
    if (peak > 1.0f) lit /= peak;

    return lit;
}

std::pair<glm::vec3, glm::vec3> sampleLightAndDir(const glm::vec3& p)
{
    glm::vec3 lit(ambient);
    glm::vec3 dir(0.0f);

    for (Light*& light : lights)
    {
        glm::vec3 toLight = light->pos - p;
        float dist = glm::length(toLight);
        if (dist > light->radius) continue;
        glm::vec3 d = glm::normalize(toLight);

        if (rayOccluded(p, d, dist, occluders)) continue;
        
        float a = 1/(1+(dist/light->falloff)*(dist/light->falloff));
        float b = 1/(1+(light->radius/light->falloff)*(light->radius/light->falloff));
        float denom = 1 - b;

        float atten = light->intensity * (a - b) / denom;
        atten = std::max(atten, 0.0f); // this line kinda useless but better safe than sorry
        lit += light->color * atten;

        dir += d * light->intensity / light->radius;
    }
    // if r, g, or b is over 1.0f then divide them all by the largest one. this
    // will force the values between 0 and 1 while still preserving the hue
    float peak = glm::max(lit.r, glm::max(lit.g, lit.b));
    if (peak > 1.0f) lit /= peak;

    // grid points that no light reached have nothing to normalise, and
    // normalising a zero vector would hand back NaNs.
    if (glm::dot(dir, dir) > 0.0f) dir = glm::normalize(dir);
    std::pair<glm::vec3, glm::vec3> pair{lit, dir};

    return pair;
}

// recursive part of the occluders walk
void Object::CollectOccluders(const glm::mat4 parentWorld, std::vector<Tri>& out)
{
    glm::mat4 world = parentWorld * transform.matrix();
    for (Object*& child : children) child->CollectOccluders(world, out);
}

// collects occluders from the static mesh and then calls Object::CollectOccluders.
void StaticMesh::CollectOccluders(const glm::mat4 parentWorld, std::vector<Tri>& out)
{
    glm::mat4 world = parentWorld * transform.matrix();
    const std::vector<unsigned int>& indices = this->getIndices();
    const std::vector<float>& vertices = this->getVertices();

    for (size_t i = 0; i + 2 < indices.size(); i += 3)
    {
        glm::vec3 tri[3];
        for (int c = 0; c < 3; c++)
        {
            size_t v = (size_t)indices[i + c] * VERTEX_FLOATS;
            glm::vec3 local(vertices[v], vertices[v + 1], vertices[v + 2]);
            tri[c] = glm::vec3(world * glm::vec4(local, 1.0f));
        }

        Tri t{tri[0], tri[1], tri[2]};
        out.push_back(t);
       
    }
    // pass parent world because not every object is a static mesh so
    // Object::CollectOccluders has to * transform.matrix() aswell.
    Object::CollectOccluders(parentWorld, out);
}

// recursive part of the lighting walk
void Object::BakeLighting(const glm::mat4 parentWorld)
{
    glm::mat4 world = parentWorld * transform.matrix();
    for (Object*& child : children) child->BakeLighting(world);
}

static float cross2D(const glm::vec2& a, const glm::vec2& b)
{
    return a.x * b.y - a.y * b.x;
}

// calculates the light value for each texel in the static meshes
// light map. then it creates the light map texture and sets it as
// the static meshes light map. finally, it calls Object::BakeLighting.
void StaticMesh::BakeLighting(const glm::mat4 parentWorld)
{
    glm::mat4 world = parentWorld * transform.matrix();
    glm::mat3 normalMat = glm::mat3(glm::transpose(glm::inverse(world)));
    const std::vector<unsigned int>& indices = this->getIndices();
    const std::vector<float>& vertices = this->getVertices();
    const xatlas::Atlas* atlas = this->getAtlas();
    const float wMargin = 1.0f / (float)atlas->width;
    const float wOffset = wMargin / 2.0f;
    const float hMargin = 1.0f / (float)atlas->height;
    const float hOffset = hMargin / 2.0f;

    std::vector<glm::vec3> pixels(atlas->width * atlas->height, glm::vec3(0.0f));
    std::vector<int> covMask(atlas->width * atlas->height, 0);

    for (size_t i = 0; i + 2 < indices.size(); i += 3)
    {
        glm::vec3 pos[3];
        glm::vec3 norm[3];
        glm::vec2 uv[3];
        float uMin = 2.0f, uMax = -1.0f;
        float vMin = 2.0f, vMax = -1.0f;

        // gets triangle corners world pos, norm, and uv.
        // also creates uv triangle bounding box
        for (int c = 0; c < 3; c++)
        {   
            size_t v = (size_t)indices[i + c] * VERTEX_FLOATS;
            pos[c]  = glm::vec3(vertices[v + 0], vertices[v + 1], vertices[v + 2]);
            norm[c] = glm::vec3(vertices[v + 5], vertices[v + 6], vertices[v + 7]);
            uv[c]   = glm::vec2(vertices[v + 8], vertices[v + 9]);

            uMin = std::min(uMin, uv[c].x);  uMax = std::max(uMax, uv[c].x);
            vMin = std::min(vMin, uv[c].y);  vMax = std::max(vMax, uv[c].y);
        }
        
        float area = cross2D(uv[1] - uv[0], uv[2] - uv[0]);
        if (fabsf(area) < 1e-8f) continue; // degenerate triangle

        // calculates world pos and world norm for each of triangles corners.
        glm::vec3 wp0 = glm::vec3(world * glm::vec4(pos[0], 1.0f));
        glm::vec3 wp1 = glm::vec3(world * glm::vec4(pos[1], 1.0f));
        glm::vec3 wp2 = glm::vec3(world * glm::vec4(pos[2], 1.0f));

        glm::vec3 wn0 = glm::normalize(normalMat * norm[0]);
        glm::vec3 wn1 = glm::normalize(normalMat * norm[1]);
        glm::vec3 wn2 = glm::normalize(normalMat * norm[2]);

        // finds the range of cols and rows inside bounding box
        int colMin = std::max(0, (int)std::floor(uMin * atlas->width  - 0.5f));
        int colMax = std::min((int)atlas->width  - 1, (int)std::ceil(uMax * atlas->width  - 0.5f));
        int rowMin = std::max(0, (int)std::floor(vMin * atlas->height - 0.5f));
        int rowMax = std::min((int)atlas->height - 1, (int)std::ceil(vMax * atlas->height - 0.5f));

        // loops through the texels inside the bounding box
        for (int row = rowMin; row <= rowMax; row++)
        {
            for (int col = colMin; col <= colMax; col++)
            {
                float texelu = col * wMargin + wOffset;
                float texelv = row * hMargin + hOffset;
                
                // calculates if texel is actually inside the triangle
                // and not just inside the bounding box.
                glm::vec2 p(texelu, texelv);
                float w0 = cross2D(uv[2] - uv[1], p - uv[1]) / area;
                float w1 = cross2D(uv[0] - uv[2], p - uv[2]) / area;
                float w2 = 1 - w0 - w1;

                if (w0 < -1e-5f || w1 < -1e-5f || w2 < -1e-5f)
                    continue;

                // gets world pos and world norm for texel
                glm::vec3 worldPos = w0*wp0 + w1*wp1 + w2*wp2;
                glm::vec3 worldNorm = glm::normalize(w0*wn0 + w1*wn1 + w2*wn2);

                // calculate light for texel
                glm::vec3 lit(ambient);

                for (Light*& light : lights)
                {
                    glm::vec3 toLight = light->pos - worldPos;
                    float dist = glm::length(toLight);
                    if (dist < 0.0001f || dist > light->radius) continue;

                    glm::vec3 dir = toLight / dist;
                    float lambert = glm::max(glm::dot(worldNorm, dir), 0.0f);
                    if (lambert <= 0) continue;

                    glm::vec3 origin = worldPos + worldNorm * 1e-3f; // shadow bias
                    if (rayOccluded(origin, dir, dist, occluders)) continue;
                    
                    float a = 1/(1+(dist/light->falloff)*(dist/light->falloff));
                    float b = 1/(1+(light->radius/light->falloff)*(light->radius/light->falloff));
                    float denom = 1 - b;

                    float atten = light->intensity * (a - b) / denom;
                    atten = std::max(atten, 0.0f);  // this line kinda useless but better safe than sorry

                    lit += light->color * lambert * atten;
                }

                // hue preservation clamp
                float peak = glm::max(lit.r, glm::max(lit.g, lit.b));
                if (peak > 1.0f) lit /= peak;

                pixels[row * atlas->width + col] = lit;
                covMask[row * atlas->width + col] = 1;
            }
        }
    }
    // loops through texels that are unlit and sets them as their
    // lit texel neighbors average. this is meant for the texels that
    // technically arent in the triangle but their corner bleeds into
    // the triangle. loops twice to be accurate which is safe because
    // the atlas has a island padding of 4 texels.
    for (int j = 0; j < 2; j++) {
        std::vector<int> copy = covMask;
        for (size_t i = 0; i < covMask.size(); i++)
        {
            if (covMask[i] == 1) continue;

            glm::vec3 total(0.0f);
            int count = 0;
            bool onTopEdge = false;
            bool onBottomEdge = false;
            bool onLeftEdge = false;
            bool onRightEdge = false;

            if (i < atlas->width)                   onTopEdge = true;
            if (i + atlas->width >= pixels.size())  onBottomEdge = true;
            if (i % atlas->width == 0)              onLeftEdge = true;
            if (i % atlas->width == atlas->width-1) onRightEdge = true;

            if (!onTopEdge) {
                if (covMask[i - atlas->width] == 1) { total += pixels[i - atlas->width]; count++; }
            }
            if (!onBottomEdge) {
                if (covMask[i + atlas->width] == 1) { total += pixels[i + atlas->width]; count++; }
            }
            if (!onLeftEdge) {
                if (covMask[i - 1] == 1) { total += pixels[i - 1]; count++; }
            }
            if (!onRightEdge) {
                if (covMask[i + 1] == 1) { total += pixels[i + 1]; count++; }
            }
            if (count > 0) {
                pixels[i] = total / float(count);
                copy[i] = 1;
            }
        }
        covMask = copy;
    }


    this->setLightMap(loadLightMap(pixels, atlas->width, atlas->height));

    
    // pass parent world because not every object is a static mesh so
    // Object::CollectOccluders has to * transform.matrix() aswell.
    Object::BakeLighting(parentWorld);
}

// original bake lighting call
void bakeSceneLighting()
{
    double start = glfwGetTime();

    for (Object*& obj : rootObjs)
        obj->CollectOccluders(glm::mat4(1.0f), occluders);
    
    std::cout << "baked " << occluders.size() << " occluder Tris"  << '\n';

    for (Object*& obj : rootObjs)
        obj->BakeLighting(glm::mat4(1.0f));

    for (const Tri& tri : occluders)
    {
        std::vector<glm::vec3> verts{tri.a, tri.b, tri.c};
        for (const glm::vec3& v : verts)
        {
            minX = std::min(minX, v.x); maxX = std::max(maxX, v.x);
            minY = std::min(minY, v.y); maxY = std::max(maxY, v.y);
            minZ = std::min(minZ, v.z); maxZ = std::max(maxZ, v.z);
        }
    }

    minX = floor(minX) - 1; minY = floor(minY) - 1; minZ = floor(minZ) - 1;
    maxX = floor(maxX) + 2; maxY = floor(maxY) + 2; maxZ = floor(maxZ) + 2;

    std::cout << "Light Grid Dimensions(-X X -Y Y -Z Z):\n";
    std::cout << minX << ' ' << maxX << ' ' << minY << ' ' << maxY << ' ' << minZ << ' ' << maxZ << '\n';
    
    // build light grid
    for (int x = minX; x <= maxX; x++)
    {
        for (int y = minY; y <= maxY; y++)
        {
            for (int z = minZ; z <= maxZ; z++)
            {
                std::pair<glm::vec3, glm::vec3> litAndDir = sampleLightAndDir(glm::vec3(x, y, z));
                lightGrid.push_back(litAndDir);
            }
        }
    }

    std::cout << "bake took " << (glfwGetTime() - start) << "s\n";
}
