#include "lighting.h"

#include "../graphics/graphics.h"

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>         // value_ptr (hand a matrix to OpenGL)
#include <xatlas/xatlas.h>

#include <vector>
#include <iostream>
#include <map>

// recursive part of the occluders walk
void Object::CollectOccluders(const glm::mat4 parentWorld, std::vector<Tri>& out)
{
    glm::mat4 world = parentWorld * transform.matrix();
    for (Object*& child : children) child->CollectOccluders(world, out);
}

// collects occluders from the static mesh and then calls Object::CollectOccluders.
void StaticMesh::CollectOccluders(const glm::mat4 parentWorld, std::vector<Tri>& out)
{
    glm::mat4 world = parentWorld * transform.matrix();
    const std::vector<unsigned int>& indices = this->getIndices();
    const std::vector<float>& vertices = this->getVertices();

    for (size_t i = 0; i + 2 < indices.size(); i += 3)
    {
        glm::vec3 tri[3];
        for (int c = 0; c < 3; c++)
        {
            size_t v = (size_t)indices[i + c] * VERTEX_FLOATS;
            glm::vec3 local(vertices[v], vertices[v + 1], vertices[v + 2]);
            tri[c] = glm::vec3(world * glm::vec4(local, 1.0f));
        }

        Tri t{tri[0], tri[1], tri[2]};
        out.push_back(t);
       
    }
    // pass parent world because not every object is a static mesh so
    // Object::CollectOccluders has to * transform.matrix() aswell.
    Object::CollectOccluders(parentWorld, out);
}

// recursive part of the lighting walk
void Object::BakeLighting(const glm::mat4 parentWorld, const std::vector<Tri>& occluders,
                          const std::vector<Light>& lights, float ambient)
{
    glm::mat4 world = parentWorld * transform.matrix();
    for (Object*& child : children) child->BakeLighting(world, occluders, lights, ambient);
}

static float cross2D(const glm::vec2& a, const glm::vec2& b)
{
    return a.x * b.y - a.y * b.x;
}

// checks if a ray starting at origin, traveling along dir, and
// stopping once it goes maxDist collides with any occluders.
//
// FUNCTION GENERATED BY CLAUDE *** AI ALERT!!! ***
static bool rayOccluded(const glm::vec3& origin, const glm::vec3& dir,
                        float maxDist, const std::vector<Tri>& tris)
{
    const float EPS = 1e-6f;

    for (const Tri& t : tris)
    {
        glm::vec3 e1 = t.b - t.a;
        glm::vec3 e2 = t.c - t.a;
        glm::vec3 p  = glm::cross(dir, e2);
        float det = glm::dot(e1, p);
        if (glm::abs(det) < EPS) continue;   // ray runs parallel to the triangle

        float invDet = 1.0f / det;
        glm::vec3 tv = origin - t.a;

        float u = glm::dot(tv, p) * invDet;
        if (u < 0.0f || u > 1.0f) continue;

        glm::vec3 q = glm::cross(tv, e1);
        float v = glm::dot(dir, q) * invDet;
        if (v < 0.0f || u + v > 1.0f) continue;

        float hit = glm::dot(e2, q) * invDet;
        if (hit > EPS && hit < maxDist) return true;   // blocked before the light
    }
    return false;
}
// FUNCTION GENERATED BY CLAUDE *** AI ALERT!!! ***

// calculates the light value for each texel in the static meshes
// light map. then it creates the light map texture and sets it as
// the static meshes light map. finally, it calls Object::BakeLighting.
void StaticMesh::BakeLighting(const glm::mat4 parentWorld, const std::vector<Tri>& occluders,
                              const std::vector<Light>& lights, float ambient)
{
    glm::mat4 world = parentWorld * transform.matrix();
    glm::mat3 normalMat = glm::mat3(glm::transpose(glm::inverse(world)));
    const std::vector<unsigned int>& indices = this->getIndices();
    const std::vector<float>& vertices = this->getVertices();
    const xatlas::Atlas* atlas = this->getAtlas();
    const float wMargin = 1.0f / (float)atlas->width;
    const float wOffset = wMargin / 2.0f;
    const float hMargin = 1.0f / (float)atlas->height;
    const float hOffset = hMargin / 2.0f;

    std::vector<glm::vec3> pixels(atlas->width * atlas->height, glm::vec3(0.0f));
    std::vector<int> covMask(atlas->width * atlas->height, 0);

    for (size_t i = 0; i + 2 < indices.size(); i += 3)
    {
        glm::vec3 pos[3];
        glm::vec3 norm[3];
        glm::vec2 uv[3];
        float uMin = 2.0f, uMax = -1.0f;
        float vMin = 2.0f, vMax = -1.0f;

        // gets triangle corners world pos, norm, and uv.
        // also creates uv triangle bounding box
        for (int c = 0; c < 3; c++)
        {   
            size_t v = (size_t)indices[i + c] * VERTEX_FLOATS;
            pos[c]  = glm::vec3(vertices[v + 0], vertices[v + 1], vertices[v + 2]);
            norm[c] = glm::vec3(vertices[v + 5], vertices[v + 6], vertices[v + 7]);
            uv[c]   = glm::vec2(vertices[v + 8], vertices[v + 9]);

            uMin = std::min(uMin, uv[c].x);  uMax = std::max(uMax, uv[c].x);
            vMin = std::min(vMin, uv[c].y);  vMax = std::max(vMax, uv[c].y);
        }
        
        float area = cross2D(uv[1] - uv[0], uv[2] - uv[0]);
        if (fabsf(area) < 1e-8f) continue; // degenerate triangle

        // calculates world pos and world norm for each of triangles corners.
        glm::vec3 wp0 = glm::vec3(world * glm::vec4(pos[0], 1.0f));
        glm::vec3 wp1 = glm::vec3(world * glm::vec4(pos[1], 1.0f));
        glm::vec3 wp2 = glm::vec3(world * glm::vec4(pos[2], 1.0f));

        glm::vec3 wn0 = glm::normalize(normalMat * norm[0]);
        glm::vec3 wn1 = glm::normalize(normalMat * norm[1]);
        glm::vec3 wn2 = glm::normalize(normalMat * norm[2]);

        // finds the range of cols and rows inside bounding box
        int colMin = std::max(0, (int)std::floor(uMin * atlas->width  - 0.5f));
        int colMax = std::min((int)atlas->width  - 1, (int)std::ceil(uMax * atlas->width  - 0.5f));
        int rowMin = std::max(0, (int)std::floor(vMin * atlas->height - 0.5f));
        int rowMax = std::min((int)atlas->height - 1, (int)std::ceil(vMax * atlas->height - 0.5f));

        // loops through the texels inside the bounding box
        for (int row = rowMin; row <= rowMax; row++)
        {
            for (int col = colMin; col <= colMax; col++)
            {
                float texelu = col * wMargin + wOffset;
                float texelv = row * hMargin + hOffset;
                
                // calculates if texel is actually inside the triangle
                // and not just inside the bounding box.
                glm::vec2 p(texelu, texelv);
                float w0 = cross2D(uv[2] - uv[1], p - uv[1]) / area;
                float w1 = cross2D(uv[0] - uv[2], p - uv[2]) / area;
                float w2 = 1 - w0 - w1;

                if (w0 < -1e-5f || w1 < -1e-5f || w2 < -1e-5f)
                    continue;

                // gets world pos and world norm for texel
                glm::vec3 worldPos = w0*wp0 + w1*wp1 + w2*wp2;
                glm::vec3 worldNorm = glm::normalize(w0*wn0 + w1*wn1 + w2*wn2);

                // calculate light for texel
                glm::vec3 lit(ambient);

                for (const Light& light : lights)
                {
                    glm::vec3 toLight = light.pos - worldPos;
                    float dist = glm::length(toLight);
                    if (dist < 0.0001f) continue;

                    glm::vec3 dir = toLight / dist;
                    float lambert = glm::max(glm::dot(worldNorm, dir), 0.0f);
                    if (lambert <= 0) continue;

                    glm::vec3 origin = worldPos + worldNorm * 1e-3f; // shadow bias
                    if (rayOccluded(origin, dir, dist, occluders)) continue;

                    float atten = light.intensity / (1.0f + (dist * dist / light.radius));

                    lit += light.color * lambert * atten;
                }

                // hue preservation clamp
                float peak = glm::max(lit.r, glm::max(lit.g, lit.b));
                if (peak > 1.0f) lit /= peak;

                pixels[row * atlas->width + col] = lit;
                covMask[row * atlas->width + col] = 1;
            }
        }
    }
    // loops through texels that are unlit and sets them as their
    // lit texel neighbors average. this is meant for the texels that
    // technically arent in the triangle but their corner bleeds into
    // the triangle. loops twice to be accurate which is safe because
    // the atlas has a island padding of 4 texels.
    for (int j = 0; j < 2; j++) {
        std::vector<int> copy = covMask;
        for (size_t i = 0; i < covMask.size(); i++)
        {
            if (covMask[i] == 1) continue;

            glm::vec3 total(0.0f);
            int count = 0;
            bool onTopEdge = false;
            bool onBottomEdge = false;
            bool onLeftEdge = false;
            bool onRightEdge = false;

            if (i < atlas->width)                   onTopEdge = true;
            if (i + atlas->width >= pixels.size())  onBottomEdge = true;
            if (i % atlas->width == 0)              onLeftEdge = true;
            if (i % atlas->width == atlas->width-1) onRightEdge = true;

            if (!onTopEdge) {
                if (covMask[i - atlas->width] == 1) { total += pixels[i - atlas->width]; count++; }
            }
            if (!onBottomEdge) {
                if (covMask[i + atlas->width] == 1) { total += pixels[i + atlas->width]; count++; }
            }
            if (!onLeftEdge) {
                if (covMask[i - 1] == 1) { total += pixels[i - 1]; count++; }
            }
            if (!onRightEdge) {
                if (covMask[i + 1] == 1) { total += pixels[i + 1]; count++; }
            }
            if (count > 0) {
                pixels[i] = total / float(count);
                copy[i] = 1;
            }
        }
        covMask = copy;
    }


    this->setLightMap(loadLightMap(pixels, atlas->width, atlas->height));

    
    // pass parent world because not every object is a static mesh so
    // Object::CollectOccluders has to * transform.matrix() aswell.
    Object::BakeLighting(parentWorld, occluders, lights, ambient);
}

// original bake lighting call
void bakeSceneLighting(const std::vector<Light>& lights,
                       std::vector<Object*>& rootObjs, float ambient)
{
    double start = glfwGetTime();

    std::vector<Tri> occluders;
    for (Object*& obj : rootObjs)
        obj->CollectOccluders(glm::mat4(1.0f), occluders);
    
    std::cout << "baked " << occluders.size() << " occluder Tris"  << '\n';

    for (Object*& obj : rootObjs)
        obj->BakeLighting(glm::mat4(1.0f), occluders, lights, ambient);

    double end = glfwGetTime();
    std::cout << "bake took " << (end - start) << "s\n";
}
